name: Docker-CI-Pipeline
on: push
jobs:
  dockerci-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
  
      - name: Set up Docker tags
        id: meta
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
  
      - name: Build image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:${{ steps.meta.outputs.sha_short }} \
                       -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:latest .

      - name: Verify Image
        run: docker images

      - name: Run Container
        run: docker run --name python-app -itd -p 80:80 ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:latest

      - name: View Container
        run: docker ps

      - name: Verify App
        run: curl -ivk http://localhost

      - name: Remove Test Container
        run: 
          docker stop python-app
          docker rm -f python-app
          
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  
      - name: Push Image to DockerHub
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:${{ steps.meta.outputs.sha_short }}
          docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:latest
